#!/usr/bin/env python3
"""Solana ecosystem snapshot pipeline — Superteam Canada bounty entry core.

Pulls FREE no-key public APIs, emits structured JSON + markdown report.
Zero external spend. Stdlib only.
"""
import json, time, urllib.request, datetime, os

OUT_DIR = os.path.join(os.path.dirname(__file__), "data")
os.makedirs(OUT_DIR, exist_ok=True)

def get(url):
    req = urllib.request.Request(url, headers={"User-Agent": "solana-eco-report/0.1"})
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.loads(r.read())

def main():
    snap = {"generated_utc": datetime.datetime.now(datetime.timezone.utc).isoformat(), "sources": {}}

    # 1. DeFiLlama: chain TVLs
    chains = get("https://api.llama.fi/v2/chains")
    sol = next(c for c in chains if c.get("name") == "Solana")
    top_chains = sorted(chains, key=lambda c: c.get("tvl", 0) or 0, reverse=True)[:10]
    snap["sources"]["defillama_chains"] = {
        "solana_tvl_usd": sol.get("tvl"),
        "solana_rank": [c["name"] for c in top_chains].index("Solana") + 1,
        "top10_by_tvl": [{"chain": c["name"], "tvl_usd": c.get("tvl")} for c in top_chains],
    }

    # 2. DeFiLlama: top Solana protocols by TVL
    protocols = get("https://api.llama.fi/protocols")
    sol_protos = [p for p in protocols if "Solana" in (p.get("chains") or [])]
    # Per-chain TVL via `chainTvls` (verified field, plain float); skip CEX entries
    def sol_tvl(p):
        v = (p.get("chainTvls") or {}).get("Solana")
        return v if isinstance(v, (int, float)) else 0
    sol_protos = [p for p in sol_protos if p.get("category") not in ("CEX", None) and sol_tvl(p) > 0]
    sol_protos.sort(key=sol_tvl, reverse=True)
    snap["sources"]["defillama_protocols"] = {
        "solana_protocol_count": len(sol_protos),
        "top15": [{"name": p["name"], "tvl_usd": sol_tvl(p), "category": p.get("category")} for p in sol_protos[:15]],
    }

    # 3. CoinGecko free tier: SOL market data
    cg = get("https://api.coingecko.com/api/v3/coins/markets?ids=solana&vs_currency=usd&price_change_percentage=24h,7d,30d")
    if cg:
        s = cg[0]
        snap["sources"]["coingecko_sol"] = {
            "price_usd": s.get("current_price"), "market_cap_usd": s.get("market_cap"),
            "rank": s.get("market_cap_rank"), "change_24h_pct": s.get("price_change_percentage_24h_in_currency"),
            "change_7d_pct": s.get("price_change_percentage_7d_in_currency"),
            "change_30d_pct": s.get("price_change_percentage_30d_in_currency"),
        }
        time.sleep(2)

    # 4. Solana public RPC: network health (epoch, TPS) — no key required
    def rpc(method, params=None):
        body = json.dumps({"jsonrpc": "2.0", "id": 1, "method": method, "params": params or []}).encode()
        req = urllib.request.Request("https://api.mainnet-beta.solana.com", data=body,
                                     headers={"Content-Type": "application/json", "User-Agent": "solana-eco-report/0.1"})
        with urllib.request.urlopen(req, timeout=30) as r:
            return json.loads(r.read())["result"]

    epoch = rpc("getEpochInfo")
    samples = rpc("getRecentPerformanceSamples", [8])
    n_tx = sum(s["numTransactions"] for s in samples)
    nv_tx = sum(s["numNonVoteTransactions"] for s in samples)
    secs = sum(s["samplePeriodSecs"] for s in samples)
    snap["sources"]['solana_rpc'] = {
        "epoch": epoch["epoch"],
        "epoch_progress_pct": round(100 * epoch["slotIndex"] / epoch["slotsInEpoch"], 2),
        "total_transactions": epoch["transactionCount"],
        "tps_total": round(n_tx / secs, 0),
        "tps_non_vote": round(nv_tx / secs, 0),
    }
    time.sleep(2)

    with open(os.path.join(OUT_DIR, "snapshot.json"), "w") as f:
        json.dump(snap, f, indent=2)

    # Markdown report
    d = snap["sources"]
    lines = [
        f"# Solana Ecosystem Snapshot — {snap['generated_utc'][:16]}Z",
        "",
        f"*Auto-generated by `pipeline.py` — zero manual steps, zero paid APIs.*",
        "",
        "## Network position",
        f"- **SOL price:** ${d['coingecko_sol']['price_usd']:,} (24h {d['coingecko_sol']['change_24h_pct']:.1f}% / 7d {d['coingecko_sol']['change_7d_pct']:.1f}% / 30d {d['coingecko_sol']['change_30d_pct']:.1f}%)",
        f"- **Market cap:** ${d['coingecko_sol']['market_cap_usd']:,} (rank #{d['coingecko_sol']['rank']})",
        f"- **Chain TVL:** ${d['defillama_chains']['solana_tvl_usd']:,.0f} — rank #{d['defillama_chains']['solana_rank']} of all tracked chains",
        "",
        "## Top 10 chains by TVL",
        "", "| # | Chain | TVL |", "|---|-------|-----|",
    ]
    for i, c in enumerate(d["defillama_chains"]["top10_by_tvl"], 1):
        lines.append(f"| {i} | {c['chain']} | ${c['tvl_usd']:,.0f} |")
    lines += ["", f"## Top Solana protocols ({d['defillama_protocols']['solana_protocol_count']} tracked total)", "",
              "| # | Protocol | Category | TVL |", "|---|----------|----------|-----|"]
    for i, p in enumerate(d["defillama_protocols"]["top15"], 1):
        lines.append(f"| {i} | {p['name']} | {p['category']} | ${(p['tvl_usd'] or 0):,.0f} |")
    net = d['solana_rpc']
    lines += ["", "## Network health", "",
              f"- **Epoch:** {net['epoch']} ({net['epoch_progress_pct']}% complete)",
              f"- **Throughput:** {net['tps_total']:,.0f} tx/s total · {net['tps_non_vote']:,.0f} tx/s non-vote",
              f"- **Lifetime transactions:** {net['total_transactions']:,}",
              "", "---", "*Data: DeFiLlama public API + CoinGecko free tier + Solana public RPC. Pipeline refreshes via GitHub Actions cron.*"]

    with open(os.path.join(OUT_DIR, "report.md"), "w") as f:
        f.write("\n".join(lines))
    print(f"OK snapshot.json={os.path.getsize(os.path.join(OUT_DIR,'snapshot.json'))}B report.md={len(chr(10).join(lines))}chars")

if __name__ == "__main__":
    main()
